FROM clojure:temurin-21-tools-deps AS build
WORKDIR /app
COPY deps.edn build.clj .
COPY src src
RUN clojure -T:build uber

FROM eclipse-temurin:21-jre-alpine
COPY --from=build /app/target/app.jar /app.jar
CMD ["/opt/java/openjdk/bin/java", "-jar", "/app.jar"]
